In [1]:
import numpy as np
import torch

In [2]:
X = np.array([160, 170, 180, 190])
X

array([160, 170, 180, 190])

In [3]:
y = np.array([0, 0, 1, 1])
y

array([0, 0, 1, 1])

In [4]:
a = 0.1
b = -17

In [5]:
def sigmoid(z):
    return 1 / (1 + torch.exp(-z))

In [6]:
learning_rate = 0.1
epochs = 1000

In [7]:
X_mean = np.mean(X)
X_mean

175.0

In [8]:
X_std = np.std(X)
X_std

11.180339887498949

In [9]:
X_norm = (X - X_mean) / X_std
print("정규화된 입력값 X_mean:", X_norm)

정규화된 입력값 X_mean: [-1.34164079 -0.4472136   0.4472136   1.34164079]


In [10]:
a = torch.tensor([0.1], requires_grad=True)
b = torch.tensor([-17.0], requires_grad=True)

In [11]:
X_tensor = torch.tensor(X_norm, dtype=torch.float32)
X_tensor

tensor([-1.3416, -0.4472,  0.4472,  1.3416])

In [12]:
y_tensor = torch.tensor(y, dtype=torch.float32)
y_tensor

tensor([0., 0., 1., 1.])

In [13]:
for epoch in range(epochs):
    z = a * X_tensor + b
    H = sigmoid(z)

    costs = -(y_tensor * torch.log(H) + (1 - y_tensor) * torch.log(1 - H)).mean()
    costs.backward()

    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad

    a.grad.zero_()
    b.grad.zero_()

    print(f"Epoch {epoch}, 평균 비용: {costs}, a: {a}, b: {b}")

Epoch 0, 평균 비용: 8.455278396606445, a: tensor([0.1447], requires_grad=True), b: tensor([-16.9500], requires_grad=True)
Epoch 1, 평균 비용: 8.4102783203125, a: tensor([0.1894], requires_grad=True), b: tensor([-16.9000], requires_grad=True)
Epoch 2, 평균 비용: 8.365280151367188, a: tensor([0.2342], requires_grad=True), b: tensor([-16.8500], requires_grad=True)
Epoch 3, 평균 비용: 8.320280075073242, a: tensor([0.2789], requires_grad=True), b: tensor([-16.8000], requires_grad=True)
Epoch 4, 평균 비용: 8.275279998779297, a: tensor([0.3236], requires_grad=True), b: tensor([-16.7500], requires_grad=True)
Epoch 5, 평균 비용: 8.230279922485352, a: tensor([0.3683], requires_grad=True), b: tensor([-16.7000], requires_grad=True)
Epoch 6, 평균 비용: 8.185281753540039, a: tensor([0.4130], requires_grad=True), b: tensor([-16.6500], requires_grad=True)
Epoch 7, 평균 비용: 8.140281677246094, a: tensor([0.4578], requires_grad=True), b: tensor([-16.6000], requires_grad=True)
Epoch 8, 평균 비용: 8.095281600952148, a: tensor([0.5025], req

In [14]:
print(f"\n학습 완료 후의 최적값: a = {a}, b = {b}")


학습 완료 후의 최적값: a = tensor([10.5137], requires_grad=True), b = tensor([-1.8875], requires_grad=True)


In [15]:
input_height = 185

input_norm = (input_height - X_mean) / X_std

z_input = a * input_norm + b

probability = sigmoid(z_input)

print(f"\n키가 {input_height}cm인 사람의 농구선수 확률: {probability}")

if probability >= 0.5:
    print("판별 결과: 농구선수입니다.")
else:
    print("판별 결과: 농구선수가 아닙니다.")


키가 185cm인 사람의 농구선수 확률: tensor([0.9995], grad_fn=<MulBackward0>)
판별 결과: 농구선수입니다.
